### ISSUE TITLE
nx-go has a new maintainer! (was: Sunsetting nx-go)

### ISSUE THREAD

**Issue by beeman** [nx-go/nx-go#102]
Hi everyone,

Just a heads-up: I'm sunsetting the project nx-go. I haven't been using this library in my own projects for some time, and maintaining it is no longer feasible for me.

The code is open source and available for anyone to fork. If you're experienced in maintaining open-source libraries (with visible activity on GitHub/NPM), feel free to reach out on Discord or Twitter (links in my profile) about taking over. Don't bother applying if you are not actively maintaining any projects as I don't have time to guide you.

Thanks for your support and contributions over the years!

**Comment by beeman** [comment]
Hey there! 

I'm excited to announce @utarwyn has reached out to me about taking over maintenance of this project! 🥳

I think this is great news for everybody using the plugin and I hope it'll become a better maintained library soon!

**Comment by utarwyn** [comment]
Welcome to the **nx-go** community :wave:
I'm happy to announce that I will be the new maintainer of the project!

### Let's introduce myself

I'm a tech-lead engineer at Natixis and I work mainly on technologies like Kotlin, Golang, Angular, React, TypeScript, Nx. I am active on open-source projects that I believe in for several years. I use Typescript in my daily life for more than 7 years, nx for more than a year. I am a user of the plugin since last year: this is why I proposed my help to continue its development 🤝 

### Next subjects I will work on:

- Add support for Nx 17 (#101)
- Rewrite code to use the new Nx standards explained in the [doc](https://nx.dev/extending-nx/tutorials/create-plugin)

Thanks @beeman for the amazing work over the years on the project.
Stay tuned for updates!

**Comment by necmettindev** [comment]
@utarwyn do you need help? i can help speed things up.

**Comment by utarwyn** [comment]
Hello @necmettindev, thank you for the proposal! I'm in vacation until 01/29... but when I get back, I'm going to push my initial work onto a new branch and any contributions will be really appreciated on it 👍

**Comment by necmettindev** [comment]
@utarwyn thanks, waiting your news

**Comment by utarwyn** [comment]
Here we go! The first beta of v3 is out 🚀 
Check the changelog here: https://github.com/nx-go/nx-go/releases/tag/v3.0.0-beta.0

I invite you to discuss this major step further in issue #107.
