### ISSUE TITLE
go-modules and go-libs

### ISSUE THREAD

**Issue by xmlking** [nx-go/nx-go#13]
I am experimenting with __go-modules__  and  __go-libs__  in __/libs__
thought you might get some better ideas to integrate into `nx-go` schematics 

https://github.com/xmlking/yeti

```bash
nx serve goapi
nx lint     goapi
nx test   goapi
```

Extra commands 
1. codegen from proto --> go into `libs/golib`
```bash
make proto
```
2.  to tag each go-module in (apps and libs)
```
make release TAG=v0.1.4
```

**Comment by beeman** [comment]
Hey @xmlking, as of version 1.6 the generator creates a `go.mod` in the project root, which makes it work pretty well (in my tests).

From looking at your project, I see you have 3 `go.mod` files, one in the root, in the app and in the lib. I couldn't get that to work, only with a single top-level `go.mod`. 

Do we need to configure something so that the app can import from the lib?

**Comment by xmlking** [comment]
@beeman thanks a lot for supporting gomods.  i think top level go.mod is good for most cases.
i was experimenting to have publishable golang libs similar to how nx support. intent was to have some libs shared to outsiders. the trick to make it work is, we have to have at least one release tag for each sub gomod.
publishing golang lib is just create a custom tag e.g., `libs/gen/go/v0.1.5`

**Comment by xmlking** [comment]
i use this shell script to release all sub modules recursively , with same tag
  https://github.com/xmlking/logger/blob/develop/Makefile#L47

**Comment by beeman** [comment]
Going to close this as the issues seems fixed, but it's good to keep this for reference.
