### ISSUE TITLE
New app generation does not work

### ISSUE THREAD

**Issue by boskiv** [nx-go/nx-go#145]
### Current Behavior

```
nx g @nx-go/nx-go:application api

 NX  Generating @nx-go/nx-go:application


 NX   Cannot read properties of undefined (reading 'replace')
```

### Expected Behavior

app generated

### Steps to Reproduce

```
☸ do-fra1-sf-cluster in ~/code/personal on ☁️  ivan.skiridomov@gmail.com(europe-west3) took 8s
❯ npx create-nx-workspace go-workspace --preset=@nx-go/nx-go

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip

 NX   Creating your v20.1.2 workspace.

✔ Installing dependencies with npm
✔ Successfully created the workspace: go-workspace.

 NX   Successfully applied preset: @nx-go/nx-go


☸ do-fra1-sf-cluster in ~/code/personal on ☁️  ivan.skiridomov@gmail.com(europe-west3) took 17s
❯ cd go-workspace

☸ do-fra1-sf-cluster in go-workspace on  master via  v1.23.3 via  v20.17.0 on ☁️  ivan.skiridomov@gmail.com(europe-west3)
❯ nx g @nx-go/nx-go:application api

 NX  Generating @nx-go/nx-go:application


 NX   Cannot read properties of undefined (reading 'replace')

Pass --verbose to see the stacktrace.
```

### Nx Report

```shell
nx report

 NX   Report complete - copy this into the issue template

Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.0

nx (global)    : 20.1.2
nx             : 20.1.2
@nx/workspace  : 20.1.2
@nx/devkit     : 20.1.2
---------------------------------------
Registered Plugins:
@nx-go/nx-go
---------------------------------------
Community plugins:
@nx-go/nx-go : 3.3.0
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "defaultBase": "master",
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "production": [
      "default"
    ],
    "sharedGlobals": [
      "{workspaceRoot}/go.work"
    ]
  },
  "plugins": [
    "@nx-go/nx-go"
  ]
}
```

### Go Version

1.23

**Comment by utarwyn** [comment]
Hello @boskiv!
Thank you for the feedback 💯 I can also reproduce it, it seems to be an undocumented breaking change in the NX devkit starting from v20. I will investigate more.

**Comment by utarwyn** [comment]
Although I try to test as much as possible the new versions of Nx and how the plugin reacts with it, I seem to have missed something. **nx-go v3.3.0 does not work correctly with Nx 20.x**, contrary to what was announced, I wish to apologize for this.

To avoid this happening in the future, I've adapted the CI to test the plugin on the oldest supported version of Nx, as well as the most recent. You can see it in action here: https://github.com/nx-go/nx-go/pull/146

<img width="554" alt="image" src="https://github.com/user-attachments/assets/e372f50c-ad65-4521-8c8b-d9f37916f2dd">

---

Finally, I'm going to propose a new release of the plugin today to fix the problem.

**Comment by boskiv** [comment]
@utarwyn hi, is there any update on it ?

**Comment by ordenador** [comment]
I have the same issue.
I tried using earlier versions of Node, such as 17 and 18, but I'm still facing the same problem...

**Comment by vsteblii** [comment]
facing the same issue

**Comment by utarwyn** [comment]
Hello! I'd like to update you here on what I've done on this subject.

This was more complicated than expected, due to a change in the way the CLI uses the “name” and “directory” arguments of the generators in Nx 20. I spent hours trying workarounds without success. In the end, I came up with an acceptable solution for using the generators without too many hitches with Nx 20 (check #147). In the event of a potential bug, I advise you to explicitly specify the “name” and “directory” arguments, for example `nx g @nx-go/nx-go:app --name=api --directory=apps/api`. This was already a way of getting around the error in this ticket.

I will release version 3.3.1 with the patch. As for the rest, sooner or later I'll have to release a new major version of nx-go that only supports Nx 20 and higher. I suggest creating a ticket to discuss this.

Sorry for the wait, hope to have solved the problem! 🙏
