### ISSUE TITLE
Weird usage with Go modules

### ISSUE THREAD

**Issue by fallion** [nx-go/nx-go#16]
When using Go modules with the provided commands `go.mod` and `go.sum` need to be in the root folder, this makes the user opt-into this pattern.

When using run-commands with cwd this can be circumvented by I feel it should either be document or have the `cwd` set to the Go project (this would be preferable as Go checks folders upwards).

I can help with this if needed.

**Comment by beeman** [comment]
Hey there @fallion - thanks for all your input on this project. Really helpful!

As you can see I've published a few fixes up and I'd like to address this one too.

Can you tell if [this fix](https://github.com/nx-go/nx-go/pull/28/files) works for you?

I've chosen to always strip off the root from the main file so that it doesn't break any existing apps.

**Comment by beeman** [comment]
Fix is published with version 1.6, let me know if you run into any issues!
