### ISSUE TITLE
Error: Cannot find module '@angular-devkit/core' after creating a brand new workspace

### ISSUE THREAD

**Issue by imjulianeral** [nx-go/nx-go#42]
Hi @beeman! Hope you're doing well. I got the following error after executing `npx nx g @nx-go/nx-go:app api` in a brand new workspace:

```bash
Cannot find module '@angular-devkit/core'
Require stack:
- /home/imjulian/go-playground/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /home/imjulian/go-playground/node_modules/@nrwl/tao/src/commands/generate.js
- /home/imjulian/go-playground/node_modules/@nrwl/tao/index.js
- /home/imjulian/go-playground/node_modules/@nrwl/cli/lib/init-local.js
- /home/imjulian/go-playground/node_modules/@nrwl/cli/bin/nx.js
```

It's a strange error because I followed all the steps defined in the `README.md` file, so there are no `angular` dependencies in my workspace, I tried to install the module anyway but I got the same error with another `angular` dependency:

```bash
Cannot find module '@angular-devkit/schematics/tools'
Require stack:
- /home/imjulian/go-playground/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /home/imjulian/go-playground/node_modules/@nrwl/tao/src/commands/generate.js
- /home/imjulian/go-playground/node_modules/@nrwl/tao/index.js
- /home/imjulian/go-playground/node_modules/@nrwl/cli/lib/init-local.js
- /home/imjulian/go-playground/node_modules/@nrwl/cli/bin/nx.js
```

I also tried to install it, but I got this error:

```bash
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@angular-devkit/schematics/tools" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/imjulian/.npm/_logs/2021-06-17T16_51_23_101Z-debug.log
```

Thanks a lot for your attention in advance. All the best :D

**Comment by toverux** [comment]
I encountered this problem too when installing this library today. The problem is that these builders actually do depend from @angular-devkit. Those are Angular CLI *builders* and not just simple Nx *executors*. I don't exactly know why the author chose to implement it like this.
I fixed it by creating an Angular app... because I needed it anyway.

But you should be able to install those dependencies without setting up a full Angular application.
> I also tried to install it, but I got this error:

Did you use something like: `npm i @angular-devkit/schematics/tools`?
If yes, the error is to be expected, it is not a valid package name. Try installing `@angular-devkit/schematics` instead.

**Comment by imjulianeral** [comment]
Thanks a lot! `npm i @angular-devkit/schematics` solved my problem. Thanks for being so kind and fast to respond. Hope this issue could be fixed in the next version, in a patch or something.

Have a great day! :+1:
