### ISSUE TITLE
Include additional assets for build

### ISSUE THREAD

**Issue by muuvmuuv** [nx-go/nx-go#64]
Creating an API often includes HTML or other files, so it would be great if we could specify them, so they get copied during build.

```json
{
  "targets": {
    "build": {
      "executor": "@nx-go/nx-go:build",
      "options": {
        "outputPath": "dist/apps/api",
        "main": "./apps/api/...",
		"inlcude": ["templates/**"]
      }
    }
  }
}

```

**Comment by phillipCouto** [comment]
@muuvmuuv is this still something of interest?

If so would you be interested in implementing it?

**Comment by muuvmuuv** [comment]
No, not anymore

**Comment by utarwyn** [comment]
Hello!
Note that since **Go v1.16**, it has been possible to include external files in the generated executable file. To do this, you need to use `go:embed`, the documentation [is available here](https://pkg.go.dev/embed@master). I therefore propose to close this ticket as there is no longer needed and it is possible to use `go:embed`. If ever a similar need arises, don't hesitate to open a new issue.
