### ISSUE TITLE
Can you have more than a main.go file in an app?

### ISSUE THREAD

**Issue by JonathanWilbur** [nx-go/nx-go#81]
I refactored my project to consist of several files, but now this plugin seems to be unaware of any file outside of `main.go`. Is there some way I can get it to compile all `.go` files within the project?

**Comment by meDavidNS** [comment]
You can specify multipe files in the main option
```
    "serve": {
      "executor": "@nx-go/nx-go:serve",
      "options": {
        "main": "main.go wire_gen.go"
      }
    },
```

**Comment by JonathanWilbur** [comment]
That is basically command injection. IMO, this should be an array of files. But I suppose that works for now. Thank you!

**Comment by beeman** [comment]
> That is basically command injection. IMO, this should be an array of files. But I suppose that works for now. Thank you!

I'm happy to land a patch that adds support for that `main` property being `string|string[]`

**Comment by saaymeen** [comment]
@JonathanWilbur I think the issue you ran into is that you only passed the `main.go` to the build executor. Since the go command is run at the nx root dir (not the app root dir), go won't know where to find the sources. This is (probably?) the reason for the `main` option. You can achieve your goal (building the whole package with all go files) by passing the apps dir (app/my-project-name) to `main`, which should imho be the default. Cheers
