### ISSUE TITLE
gow suggested in the readme.md not working properly

### ISSUE THREAD

**Issue by pedrohba1** [nx-go/nx-go#86]
I'm using go version 1.18.5 and created a fresh app with `@nx-go` and everytime I save my app when `gow` is supposed to rerun  it asks to 
```
 go: updates to go.mod needed; to update it:
        go mod tidy
   ```
   
   I'm not sure if it's best suited to open this issue on `gow` or here. Or even if this issue is related to `@nx-go` or to my enviroment at all. But I think that it is possible that someone else migth end up in the same problem.

**Comment by utarwyn** [comment]
Hello! `gow` is not suggested in the README.md anymore.
This problem seems to occur only on your project. I therefore close the ticket and invite you to reopen it if the problem concerns **nx-go** or to create [a discussion here](https://github.com/nx-go/nx-go/discussions/new/choose) to discuss a specific use case.
