### ISSUE TITLE
Cannot generate project with nx@17.0.3

### ISSUE THREAD

**Issue by tatsuya0429** [nx-go/nx-go#95]
The following error occurred when I tried to generate a project with the `nx g @nx-go/nx-go app api` command.

```
TypeError: (0 , devkit_1.readWorkspaceConfiguration) is not a function
    at ensureGoModDependency (/home/tatsuya/workspace/playground/nx-sample/node_modules/.pnpm/@nx-go+nx-go@2.8.0/node_modules/@nx-go/nx-go/src/utils/ensure-go-mod-dependency.js:15:69)
    at createGoMod (/home/tatsuya/workspace/playground/nx-sample/node_modules/.pnpm/@nx-go+nx-go@2.8.0/node_modules/@nx-go/nx-go/src/utils/create-go-mod.helper.js:15:66)
    at /home/tatsuya/workspace/playground/nx-sample/node_modules/.pnpm/@nx-go+nx-go@2.8.0/node_modules/@nx-go/nx-go/src/generators/application/generator.js:40:33
    at Generator.next (<anonymous>)
    at /home/tatsuya/workspace/playground/nx-sample/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at __awaiter (/home/tatsuya/workspace/playground/nx-sample/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:165:16)
    at default_1 (/home/tatsuya/workspace/playground/nx-sample/node_modules/.pnpm/@nx-go+nx-go@2.8.0/node_modules/@nx-go/nx-go/src/generators/application/generator.js:8:34)
    at /home/tatsuya/workspace/playground/nx-sample/node_modules/.pnpm/nx@17.0.3/node_modules/nx/src/command-line/generate/generate.js:241:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The cause of this event is probably because the `@nx/devkit` method has been deprecated for `readWorkspaceConfiguration`.

### How to reproduce

Environment
- Windows 11/WSL2 
- nx@17.0.3
- @nx-go/nx-go@2.8.0

1. Install `@nx-go/nx-go` to a nx workspace.
2. Execute this command.
`nx g @nx-go/nx-go app api`

**Comment by joannewei** [comment]
We encountered the same problem. Do we have an estimated release date for the fix?

**Comment by beeman** [comment]
> We encountered the same problem. Do we have an estimated release date for the fix?

Hi @joannewei - I should be able to find time to look at this later this week. I can't commit to a date but I'll do my best.

Also happy to review PRs if someone knows the fix.

**Comment by eliellis** [comment]
I think I have addressed this with #96, but I'm not sure you'd like to handle this. The issue was is to the fact the `readWorkspaceConfiguration` and `updateWorkspaceConfiguration` were removed in Nx 17, so I had to upgrade the workspace to 17 to assess what was available to use in their place, which led me down a path of also having to fix some other e2e / unit testing issues that arose after the workspace upgrade. @beeman not sure how you'd like to handle all of this, as it appears these fixes might be potentially breaking for those on pre-17 versions of Nx...which might require a major version bump to stick with proper semver.

**Comment by eliellis** [comment]
> > We encountered the same problem. Do we have an estimated release date for the fix?
> 
> Hi @joannewei - I should be able to find time to look at this later this week. I can't commit to a date but I'll do my best.
> 
> Also happy to review PRs if someone knows the fix.

I think I have addressed this with #96, but I'm not sure you'd like to handle this. The issue was is to the fact the `readWorkspaceConfiguration` and `updateWorkspaceConfiguration` were removed in Nx 17, so I had to upgrade the workspace to 17 to assess what was available to use in their place, which led me down a path of also having to fix some other e2e / unit testing issues that arose after the workspace upgrade. Again, I'm not sure how you'd like to handle all of this, as it appears these fixes might be potentially breaking for those on pre-17 versions of Nx...which might require a major version bump to stick with proper semver.

**Comment by joelklint** [comment]
Hi! Just discovered nx-go and gave it a spin but am unable to test it due to this. Would be awesome if we could solve this issue to unlock golang in nx17 and beyond. Where are we standing and is this currently being working on? 🙂

**Comment by zbyju** [comment]
Can we get a new release that would fix this soon?

**Comment by utarwyn** [comment]
The first beta of v3 is out with support of **Nx 17/18** 🚀
Check the changelog here: https://github.com/nx-go/nx-go/releases/tag/v3.0.0-beta.0

I invite you to discuss this major step further in issue https://github.com/nx-go/nx-go/issues/107.
